package main

import (
	"fmt"
	"os"
)

func main() {
	version := os.Getenv("VERSION")
	commit := os.Getenv("COMMIT")
	buildTime := os.Getenv("BUILD_TIME")
	builderID := os.Getenv("BUILDER_ID")

	out, _ := os.Create("version/version.generated.go")
	out.Write([]byte(fmt.Sprintf(`// Code generated by writeversion.
// DO NOT EDIT!

package version

const (
	ParentVersion = "%s"
	ParentCommit  = "%s"
	BuildTime     = "%s"
	BuilderID     = "%s"
)
`, version, commit, buildTime, builderID)))
	out.Close()
}
